Clean up jobs of google clusters
SUSE/pcw pull request #189
Opened 2023-01-26 12:01 UTC by ilausuch

https://progress.opensuse.org/issues/123499

2023-01-26 12:34 UTC, asmorodskyi commented on ocw/lib/EC2.py
> +        try:
ok I see why now , I still have questions to approach but I think it is better to discuss this verbally , so for now please ignore this comment

2023-01-26 13:01 UTC, ricardobranco777 requested changes

2023-01-26 13:01 UTC, ricardobranco777 commented on ocw/lib/provider.py
> +        res = subprocess.run(cmd.split(), env=env, capture_output=True)
For anything related to splitting shell commands, it's better and safer to use the `shlex` module.

```suggestion
        res = subprocess.run(shlex.split(cmd), env=env, capture_output=True)
```

2023-02-08 18:10 UTC, ilausuch commented
This PR is cancelled because a new approach is set using specific containers for k8s cleanup https://github.com/SUSE/pcw/pull/190

2023-02-08 18:10 UTC, closed without merging